baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'My New Hugo Site'
theme = 'hugo-book'

[params]
# https://gohugo.io/methods/time/format/
  BookDateFormat = '2 January 2006'
  BookLogo = 'logo.png'
#  BookFavicon = 'favicon.png'
  BookFavicon = 'favicon.ico'
